version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    depends_on: 
      - db
    restart: unless-stopped
    container_name: crime-reporter-api
    environment:
      - DB_HOST=db
      - DB_NAME=wcds
      - DB_LOCAL=true
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: mongo:4-bionic
    container_name: crime-reporter-db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata: