version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    container_name: crime-reporter-api
    env_file: .env
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- npm run dev

  db:
    image: mongo:4-bionic
    container_name: crime-reporter-db
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata: